# Based on https://github.com/PrakashTrove/AWS-CodeBuild-NetCore/blob/master/buildspec.yml
# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2
    
phases:
  install:
    runtime-versions:
      dotnet: 5.0
      #dotnet: latest - Latest resolve to 3.1, check this issue https://github.com/aws/aws-codebuild-docker-images/issues/414
   
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore fooddelivery/fooddelivery.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build fooddelivery/fooddelivery.csproj
      - echo Test started on `date`
      - dotnet test fooddelivery/fooddelivery.csproj
      
  post_build:
    commands:
      - echo Publish started on `date`
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/dotnet-linux-platform-bundle-app.html
      - dotnet publish -c Release -r linux-x64 --self-contained false fooddelivery/fooddelivery.csproj
      
artifacts:
  files:
    - '**/*'
  base-directory: fooddelivery/bin/Release/net5.0/linux-x64/publish/
  discard-paths: no