name: Deploy AWS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Publish
      run: dotnet publish -c Release -o '${{ github.workspace }}/out'
    
    - name: Zip package
      run: |
       cd ${{ github.workspace }}/out
       zip -r ${{ github.workspace }}/out.zip *
    
    - name: Deploy to ElasticBeansTalk
      uses: einaregilsson/beanstalk-deploy@v16
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: delivery
        environment_name: delivery-env-1
        region: sa-east-1
        version_label: ${{ github.run_id + 1 }}
        version_description: ${{ github.sha }}
        deployment_package: ${{ github.workspace }}/out.zip
